title: Blue Neuron
description: '"Everything was beautiful, and nothing hurt."'
permalink: '/stories/:title'
url: 'https://rr-n.github.io'
relative_permalinks: false
exclude:
  - script
  - vendor
  - bower.json
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - readme.md
  - package.json
  - node_modules
markdown: kramdown
plugins:
  - jekyll-avatar
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-coffeescript
  - jekyll-sitemap
  - jekyll-octicons
sass:
  style: ':compressed'
  sass_dir: assets/css/
  load_paths:
    - node_modules/
featured_orgs:
  - gcba
  - nla
  - GeoscienceAustralia
  - qld-gov-au
  - onroerenderfgoed
  - geobolivia
  - dadosgovbr
  - tisorocaba
  - canada-ca
  - wet-boew
  - e-gob
  - City-of-Helsinki
  - itschool
  - linz
  - govph
  - commonwealth-of-puerto-rico
  - The-Municipality-of-Staffanstorp
  - malmostad
  - ogdch
  - alv-ch
  - city-of-bloomington
  - cityofchattanooga
  - cityofnewyork
  - Honolulu
  - mnhrc
  - NYCComptroller
  - ArlingtonCounty
  - sfcta
  - olcf
  - ORNL
  - azgs
  - nysenate
  - State-of-Arizona
  - alphagov
  - BarnsleyCouncil
  - BristolCityCouncil
  - cabinetoffice
  - datagovuk
  - dfid
  - east-sussex-county-council
  - hmrc
  - MetOffice
  - 18f
  - CA-CST-SII
  - cfpb
  - cooperhewitt
  - erdc
  - fda
  - gsa
  - hhs
  - nasa
  - USDeptVeteransAffairs
  - virtual-world-framework
  - whitehouse
  - bundestag
  - CodeandoMexico
  - codeforeurope
  - dataviz
  - dobtco
  - KoelnAPI
  - mysociety
  - openva
  - postcode
  - sunlightlabs
  - theodi
  - codeforamerica
  - codeforaustralia
  - okfngr
  - okfn
  - nuknightlab
  - dssg
  - codeforboston
  - teampopong
